apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
  namespace: default
  labels:
    app: calc
spec:
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: soloio/example-service1:v0.2.2
        ports:
        - containerPort: 8080
          protocol: TCP