apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: webapp-common
  namespace: flux-system
spec:
  interval: 1s
  path: ./prod-cluster/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: app
  validation: server